#!/usr/bin/env python3
"""
Simple demo script that loads a graph generated by the KG pipeline,
builds OpenAI embeddings, and runs the TOG retriever for a single question.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Iterable, List, Sequence

import networkx as nx
import numpy as np
from dotenv import load_dotenv
from openai import OpenAI

from tqdm.auto import tqdm

from atlas_rag.llm_generator import LLMGenerator
from atlas_rag.retriever.inference_config import InferenceConfig
from atlas_rag.retriever.tog import TogRetriever
from atlas_rag.vectorstore.embedding_model import EmbeddingAPI

class FixedLLMGenerator(LLMGenerator):
    def _api_inference(
        self,
        message,
        max_new_tokens=8192,
        temperature=0.7,
        frequency_penalty=None,
        response_format={"type": "text"},
        return_text_only=True,
        return_thinking=False,
        reasoning_effort=None,
        **kwargs,
    ):
        import time
        from openai import NOT_GIVEN

        start_time = time.time()
        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=message,
            max_tokens=max_new_tokens,
            temperature=temperature,
            frequency_penalty=NOT_GIVEN if frequency_penalty is None else frequency_penalty,
            response_format=response_format if response_format is not None else {"type": "text"},
            timeout=120,
            reasoning_effort=NOT_GIVEN if reasoning_effort is None else reasoning_effort,
        )

        time_cost = time.time() - start_time
        content = response.choices[0].message.content

        if content is None and hasattr(response.choices[0].message, "reasoning_content"):
            content = response.choices[0].message.reasoning_content

        validate_function = kwargs.get("validate_function", None)
        content = validate_function(content, **kwargs) if validate_function else content

        if "</think>" in content and not return_thinking:
            content = content.split("</think>")[-1].strip()
        else:
            if (
                hasattr(response.choices[0].message, "reasoning_content")
                and response.choices[0].message.reasoning_content is not None
                and return_thinking
            ):
                content = "<think>" + response.choices[0].message.reasoning_content + "</think>" + content

        if return_text_only:
            return content
        else:
            completion_usage_dict = response.usage.model_dump()
            completion_usage_dict["time"] = time_cost
            return content, completion_usage_dict


def chunked(seq: Sequence[str], size: int) -> Iterable[Sequence[str]]:
    for i in range(0, len(seq), size):
        yield seq[i : i + size]


def ensure_embeddings(
    texts: List[str],
    cache_path: Path,
    order_path: Path,
    embedder: EmbeddingAPI,
    batch_size: int = 256,
    desc: str = "",
) -> np.ndarray:
    if cache_path.exists() and order_path.exists():
        stored_order = json.loads(order_path.read_text())
        if stored_order == texts:
            return np.load(cache_path)

    cache_path.parent.mkdir(parents=True, exist_ok=True)
    order_path.parent.mkdir(parents=True, exist_ok=True)

    all_embeddings = []
    progress = tqdm(total=len(texts), desc=desc or cache_path.stem, unit="item") if texts else None
    for batch in chunked(texts, batch_size):
        batch_embeddings = embedder.encode(batch)
        all_embeddings.append(batch_embeddings)
        if progress:
            progress.update(len(batch))
    if progress:
        progress.close()
    stacked = np.vstack(all_embeddings).astype(np.float32)

    np.save(cache_path, stacked)
    order_path.write_text(json.dumps(texts, ensure_ascii=False, indent=2))
    return stacked


def load_graph(graph_path: Path) -> nx.MultiDiGraph:
    if not graph_path.exists():
        raise FileNotFoundError(f"GraphML file not found: {graph_path}")
    return nx.read_graphml(graph_path.as_posix())


def maybe_truncate(text: str, max_chars: int | None) -> str:
    if not isinstance(text, str):
        text = str(text)
    if not max_chars or max_chars <= 0:
        return text
    if len(text) <= max_chars:
        return text
    return text[:max_chars]


def prepare_embeddings(
    graph: nx.MultiDiGraph,
    embedder: EmbeddingAPI,
    cache_dir: Path,
    batch_size: int,
    text_max_chars: int | None,
) -> tuple[np.ndarray, np.ndarray]:
    node_keys = list(graph.nodes())
    node_texts = [
        maybe_truncate(graph.nodes[k].get("id", k), text_max_chars) for k in node_keys
    ]

    node_emb_path = cache_dir / "tog_node_embeddings.npy"
    node_order_path = cache_dir / "tog_node_order.json"
    node_embeddings = ensure_embeddings(
        node_texts,
        node_emb_path,
        node_order_path,
        embedder,
        batch_size=batch_size,
        desc="ノード埋め込み",
    )

    edge_keys = list(graph.edges())
    edge_texts = []
    for head, tail in edge_keys:
        head_text = maybe_truncate(graph.nodes[head].get("id", head), text_max_chars)
        tail_text = maybe_truncate(graph.nodes[tail].get("id", tail), text_max_chars)
        relation = graph.edges[(head, tail)].get("relation", "related_to")
        edge_texts.append(f"{head_text} {relation} {tail_text}")

    edge_emb_path = cache_dir / "tog_edge_embeddings.npy"
    edge_order_path = cache_dir / "tog_edge_order.json"
    edge_embeddings = ensure_embeddings(
        edge_texts,
        edge_emb_path,
        edge_order_path,
        embedder,
        batch_size=batch_size,
        desc="エッジ埋め込み",
    )
    return node_embeddings, edge_embeddings


def answer_with_llm(llm: LLMGenerator, question: str, triples: List[str]) -> str:
    knowledge = "\n".join(triples) if triples else "該当するトリプルは見つかりませんでした。"
    messages = [
        {
            "role": "system",
            "content": "あなたは知識グラフのトリプルを根拠に回答する日本語のアシスタントです。"
                       "根拠が不足している場合はその旨を伝えてください。",
        },
        {
            "role": "user",
            "content": f"質問: {question}\n"
                       f"利用可能なトリプル:\n{knowledge}\n\n"
                       "これらの情報のみを根拠に、詳細に回答してください。",
        },
    ]
    return llm.generate_response(messages, max_new_tokens=512, temperature=0.2)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run TOG retrieval on a question.")
    parser.add_argument(
        "--question",
        default="日本に流通してる海産物は？",
        help="問い合わせる質問（日本語推奨）",
    )
    parser.add_argument(
        "--graph",
        default="import/niconico_2024_month/kg_graphml/niconico_2024_month_graph.graphml",
        help="GraphML ファイルのパス",
    )
    parser.add_argument(
        "--cache_dir",
        default="import/niconico_2024_month/vector_index",
        help="埋め込みをキャッシュするディレクトリ",
    )
    parser.add_argument(
        "--model",
        default="gpt-4o-mini",
        help="質問応答に使用するOpenAIチャットモデル名",
    )
    parser.add_argument(
        "--embedding_model",
        default="text-embedding-3-small",
        help="ノード／エッジ埋め込みに使用するOpenAI埋め込みモデル名",
    )
    parser.add_argument(
        "--embed_batch_size",
        type=int,
        default=64,
        help="埋め込みAPIに渡す1リクエストあたりの件数",
    )
    parser.add_argument(
        "--text_max_chars",
        type=int,
        default=1024,
        help="ノード/エッジテキストを先頭からこの文字数に制限（0以下で無制限）",
    )
    args = parser.parse_args()

    load_dotenv()
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("OPENAI_API_KEY が設定されていません (.env を確認してください)。")

    graph_path = Path(args.graph)
    cache_dir = Path(args.cache_dir)

    print("📄 グラフを読み込み中...")
    graph = load_graph(graph_path)
    print(f"   ノード数: {graph.number_of_nodes()}, エッジ数: {graph.number_of_edges()}")

    client = OpenAI()
    llm = FixedLLMGenerator(client, model_name=args.model)
    embedder = EmbeddingAPI(client, model_name=args.embedding_model)

    print("🧮 ノード／エッジ埋め込みを準備しています...")
    node_embeddings, edge_embeddings = prepare_embeddings(
        graph,
        embedder,
        cache_dir,
        args.embed_batch_size,
        args.text_max_chars,
    )
    print(f"   ノード埋め込み形状: {node_embeddings.shape}, エッジ埋め込み形状: {edge_embeddings.shape}")

    retriever = TogRetriever(
        llm_generator=llm,
        sentence_encoder=embedder,
        data={"KG": graph, "node_embeddings": node_embeddings, "edge_embeddings": edge_embeddings},
        inference_config=InferenceConfig(Dmax=5, topk=5),
    )

    print(f"❓ 質問: {args.question}")
    triples, _ = retriever.retrieve(args.question, topN=5)
    print("📚 取得したトリプル:")
    for triple in triples:
        print(f"  - {triple}")

    answer = answer_with_llm(llm, args.question, triples)
    print("\n💡 回答:")
    print(answer.strip())


if __name__ == "__main__":
    main()
